### ISSUE TITLE
Getting row count without reading every record

### ISSUE THREAD

**Issue by denisovlev** [mjakubowski84/parquet4s#157] opened 2020-07-15 15:13 UTC
Thanks for the great library!

As far as I can tell parquet4s does not provide a way to get record count without iterating through all the records from the file.
This might be problematic with very large parquet files.
It should be possible to get this information from the file metadata.

**Comment by mjakubowski84** [comment] 2020-07-15 16:17
Hi, thanks for the interest in this library.

Let's explain some things because of which the solution is not so simple.
 1. Usually you do not read a single file but many files. In case of partitioned directories (in Parquet4S supported in Akka module only) those files can be scattered across many directories and can have multiple metadata files/footers.
 2. File metadata can have but do not have to contain record count. File metadata is just a simple map of any values. In order to get the size of file(s) you have to read all blocks and use metadata available there (size is there!) and then sum it up.
 3. When you read Parquet file you can define a filter for the file. In order to get the true size of the data you read - the filter should be applied, too. If the filter predicates are satisfied with Parquet/Block metadata then we are fine, Parquet's API allows to do that: https://github.com/apache/parquet-mr/blob/apache-parquet-1.11.0/parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetFileReader.java#L752. There can be a problem if filter needs to work on a level of each particular record - then you have a scan on the whole file again.

As you see, the issue is not trivial. Parquet4S would need to introduce some kind of facade for reading metadata, etc. - using `ParquetFileReader`. Many tests including filters have to be done in order to prove if simple summing of block sizes is fine. If not then we need a fallback with iteration over records what you can do now.

**Comment by denisovlev** [comment] 2020-07-16 08:07
Is it possible to at least expose the functionality that Parquet API provides? If you do not have to support filters that would simplify that, right?

**Comment by mjakubowski84** [comment] 2020-07-16 19:31
Yes, for simplicity it can be done so that if no filter is defined then Parquet4S can sum block sizes, otherwise it fallbacks to default counting record by record.
I think that the simplest solution is just to override `size` function in https://github.com/mjakubowski84/parquet4s/blob/master/core/src/main/scala/com/github/mjakubowski84/parquet4s/ParquetReader.scala#L89

**Comment by mjakubowski84** [comment] 2020-09-04 13:29
Parquet 1.11.1 was released with a feature that can help in this issue: https://issues.apache.org/jira/browse/PARQUET-1740?jql=project%20%3D%20PARQUET%20AND%20fixVersion%20%3D%201.11.1

**Closed** 2021-04-11 16:56 UTC
