### ISSUE TITLE
Null values for generic RowParquetRecord

### ISSUE THREAD

**Issue by fr-ser** [mjakubowski84/parquet4s#204] opened 2021-05-21 06:17 UTC
Hello,

I was trying to serialize a case class such as this

```scala
case class TestRow(id: Int, maybeSomething: Option[Int])
```

When reading the parquet file back as a generic `RowParquetRecord` I don't receive anything for `maybeSomething` in case it is `None`. I would have hoped to receive a `NullValue`.

Is this intended or can this be configured?

**Comment by mjakubowski84** [comment] 2021-05-21 06:41
Hi @fr-ser,

Internally, during reading, the missing value is not stored. It is so, because Parquet itself doesn't store nulls. Column for such a record is just not present in a file.
Now it is just a matter how you access values. If you use `RowParquetRecord`'s API, like `get` it should return you `NullValue`. But if you treat it as a collection and iterate over it then you will not see it.
That could be improved if the record would be aware of the schema but in the current design, for sake of memory utilisation, it doesn't. I plan to change the design in the next major release, I will consider this issue then.

**Comment by fr-ser** [comment] 2021-05-21 15:35
> But if you treat it as a collection and iterate over it then you will not see it.

Yeah, this is how I use it

> I plan to change the design in the next major release, I will consider this issue then.

That is good to hear. In the meantime, I might tinker around a bit and see if I can just get the schema before starting to iterate and use that. Thanks though!

**Comment by marcinaylien** [comment] 2021-05-21 15:39
Check out `ParquetSchemaResolver` - this type class generates a schema.

**Comment by mjakubowski84** [comment] 2021-06-02 16:45
The issue is addressed in branch 2.x. Is awaiting next major release.

**Closed** 2021-10-21 08:46 UTC
